{
  "traceback": "Traceback (most recent call last):\n  File \"/analysistools/public_html/apps/LDlink/app/LDlink.py\", line 740, in ldproxy\n    with open('./tmp/proxy' + reference + '.txt', \"r\") as fp:\nIOError: [Errno 2] No such file or directory: './tmp/proxy0327307173.txt'\n", 
  "error": "rs75793288 is not in 1000G reference panel."
}